[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sentiment-model"
version = "0.1.0"

[tool.setuptools]
package-dir = {"" = "src_code"}

[tool.setuptools.packages.find]
where = ["src_code"]
